[package]
name = "sonicat"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bio = "0.42"
rand = "0.8"
rand_distr = "0.4"
clap = "3.1"
